// import'./components/modal'
import'./components/modal'
import'./components/accordion'
import'./components/select'
import'./components/scroll'
import'./components/header-scroll'
import'./components/nav'
import'./components/slider'
import'./components/stepper'

